/**
 * Proposal Generation Prompt
 * 
 * Synthesizes a client-facing proposal from non-technical documents only.
 * Explicitly excludes: SRS, technical specs, architecture, API schemas, tech stack internals
 * 
 * Section structure (12 sections):
 * 1. Project Overview
 * 2. Problem Statement
 * 3. Scope of Work
 * 4. Deliverables
 * 5. Estimated Timeline (placeholder — filled at Send time)
 * 6. Estimated Cost (placeholder — filled at Send time)
 * 7. Assumptions
 * 8. Exclusions
 * 9. Support
 * 10. Commercial Terms
 * 11. Acceptance
 * 12. Agency Contact
 */

export function buildProposalPrompt(
  requirementSummary: string,
  brd: string,
  prd: string,
  sow: string,
  projectTitle: string,
  dominantLanguage: string
): string {
  return `You are an expert proposal writer for a software development agency. Your task is to synthesize a professional, client-facing business proposal.

## CRITICAL CONSTRAINTS:
1. **Client-Facing Only**: Write for business stakeholders, NOT technical audiences
2. **Exclude Technical Details**: No API specs, database schemas, architecture diagrams, tech stack internals, or implementation details
3. **Use Only These Documents**:
   - Requirement Summary (high-level overview)
   - Business Requirements Document (BRD)
   - Product Requirements Document (PRD)
   - Scope of Work (SOW)
4. **DO NOT USE**: Software Requirements Specification (SRS), technical specifications, or architectural details

## REQUIRED OUTPUT STRUCTURE
Generate a proposal with EXACTLY these 12 sections, in this order, using ${dominantLanguage}:

## 1. Project Overview
Provide a concise overview of the project: what is being built, for whom, and why it matters. 2–3 short paragraphs.

## 2. Problem Statement
Clearly articulate the core business problem or opportunity the client is facing. Focus on pain points and the gap the solution fills. 1–2 paragraphs.

## 3. Scope of Work
Describe at a high level what work will be performed — the major modules, workstreams, and efforts covered in this engagement (business language, no tech specs).

## 4. Deliverables
Bulleted list of tangible outputs the client will receive: screens, workflows, integrations, documentation, etc. Keep it concrete and business-friendly.

## 5. Estimated Timeline
Render exactly as: [PLACEHOLDER: Estimated Timeline to be finalized]
Do NOT estimate or suggest any duration.

## 6. Estimated Cost
Render exactly as: [PLACEHOLDER: Project Cost to be finalized]
Do NOT suggest any price or range.

## 7. Assumptions
List the assumptions under which this proposal is valid (e.g., client provides timely feedback, existing infrastructure is stable, third-party APIs are available). Bulleted list.

## 8. Exclusions
List items explicitly NOT included in this engagement (sets clear expectations). Bulleted list.

## 9. Support
Describe post-launch support, maintenance window, warranty period, and SLA commitments. 1 paragraph.

## 10. Commercial Terms
Describe payment structure, invoicing milestones, and standard commercial terms (e.g., 50% upfront, 50% on delivery). Keep it professional but clear. Do NOT use specific currency amounts — those are in section 6.

## 11. Acceptance
Describe the acceptance criteria process: how deliverables will be reviewed, signed off, and what constitutes project completion.

## 12. Agency Contact
Placeholder block formatted as:
**Prepared by:** [Agency Name]
**Contact:** [Agency Email]
**Date:** [Current Date]

## INPUT DOCUMENTS:

### Requirement Summary:
\`\`\`
${requirementSummary}
\`\`\`

### Business Requirements Document (BRD):
\`\`\`
${brd}
\`\`\`

### Product Requirements Document (PRD):
\`\`\`
${prd}
\`\`\`

### Scope of Work (SOW):
\`\`\`
${sow}
\`\`\`

## TONE & STYLE:
- Professional, confident, business-oriented
- Clear, concise language suitable for C-level executives
- Emphasize value delivery and business outcomes
- Avoid jargon, acronyms, and technical terminology
- Use active voice and benefit-focused language

## OUTPUT FORMAT:
Use Markdown with ## headings for each section exactly as shown above (## 1. Project Overview, ## 2. Problem Statement, etc.)
For sections 5 & 6 (Timeline & Cost placeholders), use the exact text shown above in brackets.

Generate the complete 12-section proposal now:
`;
}

export const proposalTemplate = `# {PROJECT_TITLE} — Project Proposal

## 1. Project Overview
[Section content generated by AI]

---

## 2. Problem Statement
[Section content generated by AI]

---

## 3. Scope of Work
[Section content generated by AI]

---

## 4. Deliverables
[Bulleted list generated by AI]

---

## 5. Estimated Timeline
[PLACEHOLDER: Estimated Timeline to be finalized]

---

## 6. Estimated Cost
[PLACEHOLDER: Project Cost to be finalized]

---

## 7. Assumptions
[Bulleted list generated by AI]

---

## 8. Exclusions
[Bulleted list generated by AI]

---

## 9. Support
[Section content generated by AI]

---

## 10. Commercial Terms
[Section content generated by AI]

---

## 11. Acceptance
[Section content generated by AI]

---

## 12. Agency Contact
**Prepared by:** {AGENCY_NAME}
**Contact:** {AGENCY_EMAIL}
**Date:** {CURRENT_DATE}
`;
