/**
 * Proposal Generation Prompt
 * 
 * Synthesizes a client-facing proposal from non-technical documents only.
 * Explicitly excludes: SRS, technical specs, architecture, API schemas, tech stack internals
 */

export function buildProposalPrompt(
  requirementSummary: string,
  brd: string,
  prd: string,
  sow: string,
  projectTitle: string,
  dominantLanguage: string
): string {
  return `You are an expert proposal writer for a software development agency. Your task is to synthesize a professional, client-facing business proposal.

## CRITICAL CONSTRAINTS:
1. **Client-Facing Only**: Write for business stakeholders, NOT technical audiences
2. **Exclude Technical Details**: No API specs, database schemas, architecture diagrams, tech stack internals, or implementation details
3. **Use Only These Documents**:
   - Requirement Summary (high-level overview)
   - Business Requirements Document (BRD)
   - Product Requirements Document (PRD)
   - Scope of Work (SOW)
4. **DO NOT USE**: Software Requirements Specification (SRS), technical specifications, or architectural details

## REQUIRED OUTPUT STRUCTURE
Generate a proposal with EXACTLY these 10 sections, in this order, using ${dominantLanguage}:

1. **Cover Page** (metadata: client name placeholder, project title, date, agency branding)
2. **Executive Summary** (1-2 paragraphs: high-level project overview, key benefits)
3. **Our Understanding** (2-3 paragraphs: demonstrate comprehension of client's business goals, target users, pain points)
4. **Proposed Solution** (2-3 paragraphs: how we solve the problem, key features and benefits—business language only)
5. **Scope (Included / Excluded)** 
   - **Included**: List deliverables and features from BRD/PRD/SOW (business terms, not technical)
   - **Excluded**: Clear list of out-of-scope items (set expectations)
6. **Deliverables** (bulleted list: tangible outputs, milestones, deliverable types—business-friendly)
7. **Timeline (Placeholder)** (render as "[PLACEHOLDER: Estimated Timeline to be finalized]"—do NOT estimate duration)
8. **Pricing (Placeholder)** (render as "[PLACEHOLDER: Project Cost to be finalized]"—do NOT estimate cost)
9. **Support & Warranty** (1 paragraph: post-launch support, maintenance, warranty/SLA commitments)
10. **Next Steps** (2-3 sentences: call to action, contact method, approval timeline)

## INPUT DOCUMENTS:

### Requirement Summary:
\`\`\`
${requirementSummary}
\`\`\`

### Business Requirements Document (BRD):
\`\`\`
${brd}
\`\`\`

### Product Requirements Document (PRD):
\`\`\`
${prd}
\`\`\`

### Scope of Work (SOW):
\`\`\`
${sow}
\`\`\`

## TONE & STYLE:
- Professional, confident, business-oriented
- Clear, concise language suitable for C-level executives
- Emphasize value delivery and business outcomes
- Avoid jargon, acronyms, and technical terminology
- Use active voice and benefit-focused language

## OUTPUT FORMAT:
Use Markdown with clear section headings (##, ###) matching the structure above.
For sections 7 & 8 (Timeline & Pricing placeholders), use the exact text shown above in brackets.

Generate the complete proposal now:
`;
}

export const proposalTemplate = `# {PROJECT_TITLE} — Project Proposal

## 1. Cover Page
**Project Title:** {PROJECT_TITLE}
**Client:** {CLIENT_NAME}
**Date:** {CURRENT_DATE}
**Prepared by:** {AGENCY_NAME}

---

## 2. Executive Summary
[Section content generated by AI]

---

## 3. Our Understanding
[Section content generated by AI]

---

## 4. Proposed Solution
[Section content generated by AI]

---

## 5. Scope (Included / Excluded)

### Included
[Bulleted list generated by AI]

### Excluded
[Bulleted list generated by AI]

---

## 6. Deliverables
[Bulleted list generated by AI]

---

## 7. Timeline (Placeholder)
[PLACEHOLDER: Estimated Timeline to be finalized]

---

## 8. Pricing (Placeholder)
[PLACEHOLDER: Project Cost to be finalized]

---

## 9. Support & Warranty
[Section content generated by AI]

---

## 10. Next Steps
[Section content generated by AI]

---

**This proposal is valid until:** {EXPIRY_DATE_PLACEHOLDER}
`;
